name: padben
channels:
  - conda-forge
  - huggingface
  - defaults

dependencies:
  # Python Version
  - python=3.11

  # Core Dependencies from mrpc_process.py
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  
  # Development essentials
  - jupyter>=1.0.0
  - pip>=23.0.0
  
  # Pip packages (not available in conda)
  - pip:
      # Required for mrpc_process.py
      - datasets
      - huggingface-hub
      - hf_xet
      # Required for type 2 generation
      - google-genai
      - nltk
      - spacy
      - numpy
      - openai
      - aiofiles
      # For better async support
      - httpx
      # HuggingFace dependencies for paraphrasing models
      - transformers
      - torch
      - accelerate
      - sentencepiece
      - protobuf
      # Optional: for quantized models (GGUF support)
      - bitsandbytes
      # Optional: for faster inference
      - optimum
      # Fixed: python-dotenv instead of dotenv
      - python-dotenv
      - matplotlib
      - seaborn
      - tqdm
      - umap-learn>=0.5.0
      - matplotlib>=3.7.0
      - seaborn>=0.12.0
      - pathlib2>=2.3.0
      - hdbscan>=0.8.0
      - plotly>=5.15.0
      - bokeh>=3.2.0
      - pytest>=7.0.0
      - pytest-cov>=4.0.0
      - black>=23.0.0
      - flake8>=6.0.0
      - scikit-learn>=1.3.0